/**
 * Writes a docker-compose-auto-loaded `.env` file alongside the operator's
 * region-node compose file.
 *
 * **Why this exists instead of just LaunchAgent setenv:**
 * `launchctl setenv` only propagates to processes spawned BY launchd
 * after the setenv call. SSH-spawned shells (sshd child processes) and
 * Terminal.app instances that were already running at the time of
 * `bootstrap` never see the new vars — operators report `docker compose`
 * hard-failing on `${VAR:?…}` even after `launchctl getenv` confirms the
 * value is set in launchd's session table.
 *
 * The fix: docker compose auto-loads `.env` from the directory containing
 * the compose file (per the Compose spec). Writing the env file there
 * means every compose invocation — bootstrap's own phase-9 subprocess,
 * the operator's manual `docker compose up`, an unattended cron — all
 * pick up the same values without any shell-env magic.
 *
 * **Security:**
 * - File mode is 0600 (owner read/write only). Defends against the
 *   wrong-perms class of leak (another user on the same Mac reading it).
 * - File is in `.gitignore` (.env is already excluded in every
 *   opuspopuli-node template); rendered values never reach git.
 * - Values come from macOS Keychain (FileVault-encrypted at rest), not
 *   from the bootstrap process's argv or env — same risk model as the
 *   LaunchAgent plist file.
 *
 * **Atomicity:**
 * We write to a temp file in the same dir and `rename()` over the
 * destination so an interrupted bootstrap can never leave a half-written
 * `.env` (which `docker compose` would happily parse, producing services
 * with a few correct values and a few empty ones — silent corruption).
 */

import { chmod, mkdir, rename, writeFile } from 'node:fs/promises';
import { dirname, join } from 'node:path';

import { SAFE_LAUNCHCTL_VALUE_RE, SAFE_URL_RE, URL_SAFE_PASSWORD_RE } from './constants.js';

export interface EnvFileInput {
  /** Directory containing the compose file. `.env` is written as a sibling. */
  repoDir: string;
  /** All Keychain-managed values. Every field required — partial writes
   *  produce a half-broken stack, so we make the caller think about it. */
  pgsodiumRootKey: string;
  postgresPassword: string;
  jwtSecret: string;
  supabaseAnonKey: string;
  supabaseServiceRoleKey: string;
  dashboardPassword: string;
  supabaseUrl: string;
  /** Optional — only present in tunnel-enabled (non-local-only) mode. */
  tunnelToken?: string;
  /** Optional — Ollama model identifiers, when set on bootstrap CLI. */
  llmModel?: string;
  embeddingModel?: string;
}

export interface WriteEnvFileResult {
  ok: boolean;
  /** Absolute path to the written file, when ok=true. */
  path?: string;
  reason?: string;
}

/**
 * Validate that every interpolated value is safe to embed in a `.env` line.
 * Pulls from the same regex set as launchagent.ts — base64/base64url/JWT
 * chars plus URL chars for SUPABASE_URL. Reject anything outside.
 *
 * The .env format is naive: it doesn't quote, doesn't escape, doesn't
 * handle multi-line values. A value containing a literal newline would
 * silently break the rest of the file. Reject early.
 */
function validate(input: EnvFileInput): string | undefined {
  const urlSafe: Array<[string, string]> = [
    ['postgresPassword', input.postgresPassword],
    ['dashboardPassword', input.dashboardPassword],
  ];
  for (const [name, value] of urlSafe) {
    if (!URL_SAFE_PASSWORD_RE.test(value)) {
      return `${name} contains characters outside the URL-safe alphabet`;
    }
  }
  const launchctlSafe: Array<[string, string]> = [
    ['jwtSecret', input.jwtSecret],
    ['supabaseAnonKey', input.supabaseAnonKey],
    ['supabaseServiceRoleKey', input.supabaseServiceRoleKey],
    ['pgsodiumRootKey', input.pgsodiumRootKey],
  ];
  for (const [name, value] of launchctlSafe) {
    if (!SAFE_LAUNCHCTL_VALUE_RE.test(value)) {
      return `${name} contains characters not safe for a .env file`;
    }
  }
  if (!SAFE_URL_RE.test(input.supabaseUrl)) {
    return `supabaseUrl contains characters not safe for a .env file`;
  }
  if (input.tunnelToken !== undefined && !SAFE_LAUNCHCTL_VALUE_RE.test(input.tunnelToken)) {
    return `tunnelToken contains characters not safe for a .env file`;
  }
  return undefined;
}

/**
 * Render the .env content. Pure function — caller writes it. Stable
 * ordering (sorted by section) so diffs across bootstrap re-runs are
 * meaningful (only changed values show up).
 */
export function renderEnvFile(input: EnvFileInput): string {
  const lines: string[] = [
    '# Auto-generated by `create-op-node bootstrap`.',
    '# Docker Compose auto-loads this file from the same directory as',
    '# the compose file. Do NOT edit by hand — re-run bootstrap to',
    '# regenerate. NEVER commit (already in .gitignore).',
    '',
    '# ---- Postgres / pgsodium ----',
    `POSTGRES_PASSWORD=${input.postgresPassword}`,
    `PGSODIUM_ROOT_KEY=${input.pgsodiumRootKey}`,
    '',
    '# ---- Supabase auth / API ----',
    `JWT_SECRET=${input.jwtSecret}`,
    `SUPABASE_URL=${input.supabaseUrl}`,
    `SUPABASE_ANON_KEY=${input.supabaseAnonKey}`,
    `SUPABASE_SERVICE_ROLE_KEY=${input.supabaseServiceRoleKey}`,
    `DASHBOARD_PASSWORD=${input.dashboardPassword}`,
    '',
  ];
  if (input.tunnelToken !== undefined) {
    lines.push('# ---- Cloudflare Tunnel ----', `TUNNEL_TOKEN=${input.tunnelToken}`, '');
  }
  if (input.llmModel !== undefined || input.embeddingModel !== undefined) {
    lines.push('# ---- Ollama ----');
    if (input.llmModel !== undefined) lines.push(`LLM_MODEL=${input.llmModel}`);
    if (input.embeddingModel !== undefined) lines.push(`EMBEDDINGS_MODEL=${input.embeddingModel}`);
    lines.push('');
  }
  return lines.join('\n');
}

/**
 * Validate + write atomically with mode 0600. Returns the absolute path
 * on success so the caller can log it. Failure returns ok=false with a
 * reason; caller decides whether to bail or continue.
 */
export async function writeEnvFile(input: EnvFileInput): Promise<WriteEnvFileResult> {
  const reason = validate(input);
  if (reason) return { ok: false, reason };

  const target = join(input.repoDir, '.env');
  const tmp = `${target}.tmp.${process.pid}`;
  const content = renderEnvFile(input);

  try {
    await mkdir(dirname(target), { recursive: true });
    await writeFile(tmp, content, { mode: 0o600 });
    await chmod(tmp, 0o600); // belt + suspenders; writeFile mode honors umask
    await rename(tmp, target); // atomic on POSIX
    return { ok: true, path: target };
  } catch (err) {
    return { ok: false, reason: `writing ${target} failed: ${(err as Error).message}` };
  }
}
