/**
 * Renders the `bin/op-compose` wrapper script that lives in the operator's
 * region-node repo.
 *
 * **Why a wrapper instead of a `.env` file:**
 * The project's vault-first principle (#811) says runtime secrets read via
 * `secretsProvider.getSecret()` at point of use; env-on-disk is reserved
 * for bootstrap-critical config. The bootstrap-layer secrets (Postgres
 * password, JWT secret, Supabase admin tokens) ARE bootstrap-critical
 * (Postgres / kong / gotrue can't start without them, and Vault doesn't
 * exist until Postgres is up) — but they don't need to LIVE on disk in
 * plaintext to be available at compose-invocation time.
 *
 * This wrapper reads them from macOS Keychain (FileVault-encrypted at
 * rest) on every invocation and exports them only into the docker compose
 * subprocess's env. No plaintext .env file ever lands on disk; the
 * Keychain is the sole persistent store.
 *
 * **Why launchctl setenv isn't sufficient:**
 * `launchctl setenv` only propagates to processes spawned by launchd
 * AFTER the setenv call. SSH-spawned shells (sshd children) and
 * already-running Terminal.app instances never see the new vars, so
 * `docker compose` hard-fails on `${VAR:?…}` even though `launchctl
 * getenv` confirms launchd has them. The wrapper is shell-agnostic and
 * works the same in every invocation context.
 *
 * **Operator workflow:**
 *   $ ./bin/op-compose -f docker-compose-prod.yml up -d
 *   $ ./bin/op-compose -f docker-compose-prod.yml pull
 *   $ ./bin/op-compose -f docker-compose-prod.yml down
 *
 * The wrapper accepts every argument `docker compose` accepts.
 *
 * **Security:**
 * - Script is mode 0755 (executable, world-readable). The script ITSELF
 *   has no secrets — it's a static shell script with the region name
 *   baked in. The secrets only exist in process env for the lifetime
 *   of the docker compose invocation.
 * - Region name is the only baked-in value (used to scope the Keychain
 *   service identifier `org.opuspopuli.<region>`); shell-injection is
 *   prevented by the region-validation regex in bootstrap.ts.
 * - Errors when a required Keychain entry is missing point the operator
 *   at `create-op-node bootstrap`.
 */

const REGION_RE = /^[a-z0-9-]{2,32}$/;

/** URL-shape regex for values baked into the wrapper as
 *  `export PROMPT_SERVICE_URL="…"`. Matches what bootstrap.ts validates
 *  via SAFE_URL_RE — letters, digits, `:`, `/`, `_`, `-`, `.`. Reject
 *  shell metacharacters that would inject when the wrapper sources. */
const PROMPT_SERVICE_URL_RE = /^[A-Za-z0-9:/_.-]+$/;

export interface OpComposeScriptInput {
  /** Region slug — gets interpolated into the Keychain service identifier
   *  `org.opuspopuli.<region>`. Validated against the same regex bootstrap
   *  uses, so a tampered call site can't inject shell metacharacters. */
  region: string;
  /** Default value the wrapper sets for `PROMPT_SERVICE_URL` when nothing
   *  in the docker compose service-level env overrides it. For
   *  `region-with-prompts` deployments this is the in-network address
   *  `http://opuspopuli-prompts:3210` (and the overlay still wins via
   *  service-level env). For `region` (remote prompts) it's whatever URL
   *  the operator pointed at — typically https://prompts.opuspopuli.org.
   *  Omit and the wrapper won't export PROMPT_SERVICE_URL at all. */
  promptServiceUrl?: string;
}

/**
 * Render the wrapper script. Pure function — caller writes it to disk and
 * `chmod 0755`s the result.
 *
 * Throws on an invalid region label rather than emit a script with a
 * shell-injectable service identifier.
 */
export function renderOpComposeScript(input: OpComposeScriptInput): string {
  if (!REGION_RE.test(input.region)) {
    throw new Error(
      `region ${JSON.stringify(input.region)} contains characters not allowed in a launchd / Keychain service identifier`,
    );
  }
  if (input.promptServiceUrl !== undefined && !PROMPT_SERVICE_URL_RE.test(input.promptServiceUrl)) {
    throw new Error(
      `promptServiceUrl ${JSON.stringify(input.promptServiceUrl)} contains characters not allowed in a wrapper export`,
    );
  }
  const promptServiceUrlExport =
    input.promptServiceUrl !== undefined
      ? `# Backend services call prompt-service via this URL. Service-level env
# from docker-compose-prompt-service.yml overlay (when layered) wins
# over this default — so colocated deployments still hit
# http://opuspopuli-prompts:3210 even though we may have a public URL
# baked in here.
export PROMPT_SERVICE_URL="\${PROMPT_SERVICE_URL:-${input.promptServiceUrl}}"

`
      : '';

  return `#!/bin/bash
# op-compose — wrapper that reads region secrets from macOS Keychain just
# before invoking \`docker compose\`. Auto-generated by
# \`create-op-node bootstrap --region ${input.region}\`. Do not edit by
# hand; re-run bootstrap to regenerate.
#
# Why: launchctl setenv only propagates to launchd-spawned processes, so
# SSH shells and pre-existing Terminal.app instances never see the env
# vars bootstrap exports. This wrapper hydrates the docker compose
# subprocess directly, so every invocation works regardless of how the
# operator's shell was started.
#
# Usage:
#   ./bin/op-compose -f docker-compose-prod.yml up -d
#   ./bin/op-compose -f docker-compose-prod.yml pull
#   ./bin/op-compose -f docker-compose-prod.yml down

set -euo pipefail

SVC="org.opuspopuli.${input.region}"

# macOS \`security\` exit codes:
#   0  = success
#   36 = errSecInteractionNotAllowed (keychain is locked)
#   44 = errSecItemNotFound (entry doesn't exist)
# Earlier wrapper versions conflated 36 and 44 into a generic "missing"
# message, which sent operators down the wrong path (re-bootstrap when
# the real fix was \`security unlock-keychain\`).
require_secret() {
  local account="$1"
  local value
  local rc=0
  value=$(security find-generic-password -s "$SVC" -a "$account" -w 2>/dev/null) || rc=$?
  case "$rc" in
    0)
      printf '%s' "$value"
      return 0
      ;;
    36)
      cat >&2 <<EOM
op-compose: keychain is LOCKED — could not read entry '$account'.
SSH sessions don't auto-unlock the login keychain. Unlock with:
  security unlock-keychain ~/Library/Keychains/login.keychain-db
Then re-run this command.
EOM
      exit 1
      ;;
    44)
      cat >&2 <<EOM
op-compose: keychain entry '$account' is MISSING under service '$SVC'.
Run: create-op-node bootstrap --region ${input.region}
EOM
      exit 1
      ;;
    *)
      echo "op-compose: \`security\` failed reading '$account' (exit $rc)." >&2
      exit 1
      ;;
  esac
}

# Used for entries that may legitimately not exist (TUNNEL_TOKEN in
# local-only mode, prompt-service secrets when colocation isn't active).
# Treats exit 44 (missing) as a silent OK — returns empty string.
# Treats exit 36 (locked) as a hard error, since the require_secret calls
# at the top of the wrapper would have caught this first in normal use;
# reaching this path means something else bypassed the lock check.
optional_secret() {
  local account="$1"
  local value
  local rc=0
  value=$(security find-generic-password -s "$SVC" -a "$account" -w 2>/dev/null) || rc=$?
  case "$rc" in
    0) printf '%s' "$value" ;;
    44) ;; # legitimately absent — empty string is correct
    36)
      cat >&2 <<EOM
op-compose: keychain is LOCKED — could not probe optional entry '$account'.
Unlock with: security unlock-keychain ~/Library/Keychains/login.keychain-db
EOM
      exit 1
      ;;
    *)
      echo "op-compose: \`security\` failed reading '$account' (exit $rc)." >&2
      exit 1
      ;;
  esac
}

# Bootstrap-critical: Postgres + Supabase admin credentials.
export PGSODIUM_ROOT_KEY="$(require_secret pgsodium-root-key)"
export POSTGRES_PASSWORD="$(require_secret postgres-password)"
export JWT_SECRET="$(require_secret jwt-secret)"
export SUPABASE_ANON_KEY="$(require_secret supabase-anon-key)"
export SUPABASE_SERVICE_ROLE_KEY="$(require_secret supabase-service-role-key)"
export DASHBOARD_PASSWORD="$(require_secret dashboard-password)"

# API Gateway HMAC secret. The gateway signs gateway→microservice requests
# with this (X-HMAC-Auth) in EVERY mode, so it is required. API_KEYS is the
# JSON map each microservice reads to verify the caller; the api-gateway's
# key MUST equal GATEWAY_HMAC_SECRET. We render the JSON from the single
# Keychain value here so the compose \`\${GATEWAY_HMAC_SECRET:-…}\` /
# \`\${API_KEYS:-…}\` well-known defaults are always overridden with a real
# per-node value.
export GATEWAY_HMAC_SECRET="$(require_secret gateway-hmac-secret)"
export API_KEYS="{\\"api-gateway\\":\\"\${GATEWAY_HMAC_SECRET}\\"}"

# Grafana admin password — overrides the compose \`admin\`/\`admin\` default.
export GRAFANA_ADMIN_PASSWORD="$(require_secret grafana-admin-password)"

# AUTH_JWT_SECRET historically equals JWT_SECRET in dev/UAT — supply that
# default if the operator hasn't set one independently.
export AUTH_JWT_SECRET="\${AUTH_JWT_SECRET:-$JWT_SECRET}"

# Optional: Cloudflare Tunnel token (only present in non-local-only mode).
TUNNEL_TOKEN_VAL="$(optional_secret tunnel-token)"
if [ -n "$TUNNEL_TOKEN_VAL" ]; then
  export TUNNEL_TOKEN="$TUNNEL_TOKEN_VAL"
fi

# SUPABASE_URL is not a secret — read from env if the operator set one,
# default to localhost for --local-only.
export SUPABASE_URL="\${SUPABASE_URL:-http://localhost:8000}"

${promptServiceUrlExport}# prompt-service credentials. Always exported — harmless when the operator
# is NOT colocating prompt-service (the main compose doesn't read these
# vars; the overlay does). The PROMPT_SERVICE_API_KEYS list is built from
# the operator's region + the single HMAC key in Keychain, matching the
# prompt-service env format \`<region>:<key>,<region>:<key>,…\`.
PROMPTS_DB_PASSWORD_VAL="$(optional_secret prompts-db-password)"
PROMPT_SERVICE_API_KEY_VAL="$(optional_secret prompt-service-api-key)"
PROMPT_SERVICE_ADMIN_API_KEY_VAL="$(optional_secret prompt-service-admin-api-key)"
if [ -n "$PROMPTS_DB_PASSWORD_VAL" ]; then
  export PROMPTS_DB_PASSWORD="$PROMPTS_DB_PASSWORD_VAL"
fi
if [ -n "$PROMPT_SERVICE_API_KEY_VAL" ]; then
  export PROMPT_SERVICE_API_KEY="$PROMPT_SERVICE_API_KEY_VAL"
  # API_KEYS env on prompt-service is \`<region>:<key>,…\` — render the
  # single-region pair here so prompt-service accepts the same key the
  # backend sends. The prompts team adds additional regions on the
  # central deployment for Phase 2.
  export PROMPT_SERVICE_API_KEYS="${input.region}:$PROMPT_SERVICE_API_KEY_VAL"
fi
if [ -n "$PROMPT_SERVICE_ADMIN_API_KEY_VAL" ]; then
  export PROMPT_SERVICE_ADMIN_API_KEYS="$PROMPT_SERVICE_ADMIN_API_KEY_VAL"
fi

exec docker compose "$@"
`;
}
