/**
 * Renders the `bin/op-compose` wrapper script that lives in the operator's
 * region-node repo.
 *
 * **Why a wrapper instead of a `.env` file:**
 * The project's vault-first principle (#811) says runtime secrets read via
 * `secretsProvider.getSecret()` at point of use; env-on-disk is reserved
 * for bootstrap-critical config. The bootstrap-layer secrets (Postgres
 * password, JWT secret, Supabase admin tokens) ARE bootstrap-critical
 * (Postgres / kong / gotrue can't start without them, and Vault doesn't
 * exist until Postgres is up) — but they don't need to LIVE on disk in
 * plaintext to be available at compose-invocation time.
 *
 * This wrapper reads them from macOS Keychain (FileVault-encrypted at
 * rest) on every invocation and exports them only into the docker compose
 * subprocess's env. No plaintext .env file ever lands on disk; the
 * Keychain is the sole persistent store.
 *
 * **Why launchctl setenv isn't sufficient:**
 * `launchctl setenv` only propagates to processes spawned by launchd
 * AFTER the setenv call. SSH-spawned shells (sshd children) and
 * already-running Terminal.app instances never see the new vars, so
 * `docker compose` hard-fails on `${VAR:?…}` even though `launchctl
 * getenv` confirms launchd has them. The wrapper is shell-agnostic and
 * works the same in every invocation context.
 *
 * **Operator workflow:**
 *   $ ./bin/op-compose -f docker-compose-prod.yml up -d
 *   $ ./bin/op-compose -f docker-compose-prod.yml pull
 *   $ ./bin/op-compose -f docker-compose-prod.yml down
 *
 * The wrapper accepts every argument `docker compose` accepts.
 *
 * **Security:**
 * - Script is mode 0755 (executable, world-readable). The script ITSELF
 *   has no secrets — it's a static shell script with the region name
 *   baked in. The secrets only exist in process env for the lifetime
 *   of the docker compose invocation.
 * - Region name is the only baked-in value (used to scope the Keychain
 *   service identifier `org.opuspopuli.<region>`); shell-injection is
 *   prevented by the region-validation regex in bootstrap.ts.
 * - Errors when a required Keychain entry is missing point the operator
 *   at `create-op-node bootstrap`.
 */

const REGION_RE = /^[a-z0-9-]{2,32}$/;

export interface OpComposeScriptInput {
  /** Region slug — gets interpolated into the Keychain service identifier
   *  `org.opuspopuli.<region>`. Validated against the same regex bootstrap
   *  uses, so a tampered call site can't inject shell metacharacters. */
  region: string;
}

/**
 * Render the wrapper script. Pure function — caller writes it to disk and
 * `chmod 0755`s the result.
 *
 * Throws on an invalid region label rather than emit a script with a
 * shell-injectable service identifier.
 */
export function renderOpComposeScript(input: OpComposeScriptInput): string {
  if (!REGION_RE.test(input.region)) {
    throw new Error(
      `region ${JSON.stringify(input.region)} contains characters not allowed in a launchd / Keychain service identifier`,
    );
  }
  return `#!/bin/bash
# op-compose — wrapper that reads region secrets from macOS Keychain just
# before invoking \`docker compose\`. Auto-generated by
# \`create-op-node bootstrap --region ${input.region}\`. Do not edit by
# hand; re-run bootstrap to regenerate.
#
# Why: launchctl setenv only propagates to launchd-spawned processes, so
# SSH shells and pre-existing Terminal.app instances never see the env
# vars bootstrap exports. This wrapper hydrates the docker compose
# subprocess directly, so every invocation works regardless of how the
# operator's shell was started.
#
# Usage:
#   ./bin/op-compose -f docker-compose-prod.yml up -d
#   ./bin/op-compose -f docker-compose-prod.yml pull
#   ./bin/op-compose -f docker-compose-prod.yml down

set -euo pipefail

SVC="org.opuspopuli.${input.region}"

require_secret() {
  local account="$1"
  local value
  if ! value=$(security find-generic-password -s "$SVC" -a "$account" -w 2>/dev/null); then
    echo "op-compose: missing Keychain entry '$account' under service '$SVC'." >&2
    echo "Run: create-op-node bootstrap --region ${input.region}" >&2
    exit 1
  fi
  printf '%s' "$value"
}

optional_secret() {
  local account="$1"
  security find-generic-password -s "$SVC" -a "$account" -w 2>/dev/null || true
}

# Bootstrap-critical: Postgres + Supabase admin credentials.
export PGSODIUM_ROOT_KEY="$(require_secret pgsodium-root-key)"
export POSTGRES_PASSWORD="$(require_secret postgres-password)"
export JWT_SECRET="$(require_secret jwt-secret)"
export SUPABASE_ANON_KEY="$(require_secret supabase-anon-key)"
export SUPABASE_SERVICE_ROLE_KEY="$(require_secret supabase-service-role-key)"
export DASHBOARD_PASSWORD="$(require_secret dashboard-password)"

# AUTH_JWT_SECRET historically equals JWT_SECRET in dev/UAT — supply that
# default if the operator hasn't set one independently.
export AUTH_JWT_SECRET="\${AUTH_JWT_SECRET:-$JWT_SECRET}"

# Optional: Cloudflare Tunnel token (only present in non-local-only mode).
TUNNEL_TOKEN_VAL="$(optional_secret tunnel-token)"
if [ -n "$TUNNEL_TOKEN_VAL" ]; then
  export TUNNEL_TOKEN="$TUNNEL_TOKEN_VAL"
fi

# SUPABASE_URL is not a secret — read from env if the operator set one,
# default to localhost for --local-only.
export SUPABASE_URL="\${SUPABASE_URL:-http://localhost:8000}"

exec docker compose "$@"
`;
}
