/**
 * Small pure helpers for the local-state-only bits of `create-op-node init`:
 * generating a fresh pgsodium master key, and rendering a region's
 * `prod.tfvars` file.
 *
 * Both are side-effect free — they produce strings the caller decides what to
 * do with. Tests exercise them in isolation.
 */

import { randomBytes } from 'node:crypto';

/**
 * Generate a 32-byte (256-bit) key encoded as 64 lowercase hex characters —
 * the format `pgsodium` expects in `PGSODIUM_ROOT_KEY` and what the runbook
 * documents. The bytes come from Node's CSPRNG.
 */
export function generatePgsodiumRootKey(): string {
  return randomBytes(32).toString('hex');
}

export interface ProdTfvarsInput {
  /** Resource-name prefix used across the Terraform module
   *  (e.g. `<project>-tunnel-prod`). Defaults to `opuspopuli`. */
  project?: string;
  /** Operator's registered domain in Cloudflare (e.g. `civicfeed.tx`). */
  domain: string;
  /** Subdomain for the API tunnel (e.g. `api`). Default: `api`. */
  apiSubdomain?: string;
  /** Subdomain for the Cloudflare Pages frontend (e.g. `app`). Default: `app`. */
  appSubdomain?: string;
  /** Local port the API Gateway listens on inside the Studio. Default: 8080. */
  tunnelApiPort?: number;
  /** R2 region hint. Default: `WNAM` (Western North America). */
  r2LocationHint?: string;
}

/**
 * Render a region operator's `prod.tfvars` from their answers. Mirrors the
 * shape of `opuspopuli-node/infra/cloudflare/environments/prod.tfvars.example`
 * so the file lands ready for the cloudflare-infra workflow without any
 * post-processing.
 *
 * The output is the literal file contents — caller writes it to the repo via
 * the GitHub Contents API (`commitFile`).
 */
export function renderProdTfvars(input: ProdTfvarsInput): string {
  const project = input.project ?? 'opuspopuli';
  const api = input.apiSubdomain ?? 'api';
  const app = input.appSubdomain ?? 'app';
  const port = input.tunnelApiPort ?? 8080;
  const r2 = input.r2LocationHint ?? 'WNAM';

  return `# =============================================================================
# Production environment — generated by create-op-node init
# =============================================================================
# Region-specific values for the OpusPopuli/opuspopuli-node template's
# infra/cloudflare/ Terraform. Edit by hand to tweak.

project = ${JSON.stringify(project)}

domain_name = ${JSON.stringify(input.domain)}

api_subdomain = ${JSON.stringify(api)}
app_subdomain = ${JSON.stringify(app)}

tunnel_api_port = ${port}

r2_location_hint = ${JSON.stringify(r2)}

enable_tunnel   = true
enable_frontend = true
enable_r2       = true
`;
}
