import { afterEach, beforeEach, describe, expect, it } from 'vitest';
import { mkdtemp, readFile, rm, stat } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';

import { renderEnvFile, writeEnvFile } from '../src/lib/env-file.js';

const BASE = {
  pgsodiumRootKey: 'a'.repeat(64),
  postgresPassword: 'base64url-pw-no-plus-or-slash',
  jwtSecret: 'base64-jwt-secret/with+plus=ok',
  supabaseAnonKey: 'eyJhbGciOiJIUzI1NiJ9.eyJyb2xlIjoiYW5vbiJ9.sig',
  supabaseServiceRoleKey: 'eyJhbGciOiJIUzI1NiJ9.eyJyb2xlIjoic3J2In0.sig',
  dashboardPassword: 'dashboard-pw-base64url',
  supabaseUrl: 'http://localhost:8000',
};

describe('renderEnvFile', () => {
  it('emits every required key with the value verbatim', () => {
    const out = renderEnvFile({ repoDir: '/tmp/x', ...BASE });
    expect(out).toMatch(/^POSTGRES_PASSWORD=base64url-pw-no-plus-or-slash$/m);
    expect(out).toMatch(/^PGSODIUM_ROOT_KEY=a{64}$/m);
    expect(out).toMatch(/^JWT_SECRET=base64-jwt-secret\/with\+plus=ok$/m);
    expect(out).toMatch(/^SUPABASE_URL=http:\/\/localhost:8000$/m);
    expect(out).toMatch(/^SUPABASE_ANON_KEY=eyJ/m);
    expect(out).toMatch(/^SUPABASE_SERVICE_ROLE_KEY=eyJ/m);
    expect(out).toMatch(/^DASHBOARD_PASSWORD=dashboard-pw-base64url$/m);
  });

  it('omits TUNNEL_TOKEN section in local-only mode (tunnelToken undefined)', () => {
    const out = renderEnvFile({ repoDir: '/tmp/x', ...BASE });
    expect(out).not.toContain('TUNNEL_TOKEN');
  });

  it('includes TUNNEL_TOKEN when provided', () => {
    const out = renderEnvFile({ repoDir: '/tmp/x', ...BASE, tunnelToken: 'eyJ.tunnel.token' });
    expect(out).toMatch(/^TUNNEL_TOKEN=eyJ\.tunnel\.token$/m);
  });

  it('includes LLM + EMBEDDINGS sections when set', () => {
    const out = renderEnvFile({
      repoDir: '/tmp/x',
      ...BASE,
      llmModel: 'qwen2.5:72b',
      embeddingModel: 'nomic-embed-text',
    });
    expect(out).toMatch(/^LLM_MODEL=qwen2\.5:72b$/m);
    expect(out).toMatch(/^EMBEDDINGS_MODEL=nomic-embed-text$/m);
  });

  it('leads with a "do not edit / never commit" banner', () => {
    const out = renderEnvFile({ repoDir: '/tmp/x', ...BASE });
    expect(out).toMatch(/Auto-generated by `create-op-node bootstrap`/);
    expect(out).toMatch(/NEVER commit/);
  });
});

describe('writeEnvFile', () => {
  let dir: string;
  beforeEach(async () => {
    dir = await mkdtemp(join(tmpdir(), 'op-envfile-'));
  });
  afterEach(async () => {
    await rm(dir, { recursive: true, force: true });
  });

  it('writes .env at mode 0600 with the rendered content', async () => {
    const r = await writeEnvFile({ repoDir: dir, ...BASE });
    expect(r.ok).toBe(true);
    expect(r.path).toBe(join(dir, '.env'));

    const contents = await readFile(r.path!, 'utf8');
    expect(contents).toContain('POSTGRES_PASSWORD=base64url-pw-no-plus-or-slash');

    const st = await stat(r.path!);
    expect(st.mode & 0o777).toBe(0o600);
  });

  it('overwrites an existing .env atomically (no partial-write window)', async () => {
    // First write
    await writeEnvFile({ repoDir: dir, ...BASE });
    // Second write with a different POSTGRES_PASSWORD
    const r = await writeEnvFile({ repoDir: dir, ...BASE, postgresPassword: 'rotated-value-here' });
    expect(r.ok).toBe(true);
    const contents = await readFile(r.path!, 'utf8');
    expect(contents).toContain('POSTGRES_PASSWORD=rotated-value-here');
    expect(contents).not.toContain('POSTGRES_PASSWORD=base64url-pw-no-plus-or-slash');
  });

  it('rejects a postgres password containing URL-reserved chars', async () => {
    const r = await writeEnvFile({ repoDir: dir, ...BASE, postgresPassword: 'has/slash' });
    expect(r.ok).toBe(false);
    expect(r.reason).toMatch(/postgresPassword.*URL-safe/);
  });

  it('rejects a dashboard password containing URL-reserved chars', async () => {
    const r = await writeEnvFile({ repoDir: dir, ...BASE, dashboardPassword: 'has+plus' });
    expect(r.ok).toBe(false);
    expect(r.reason).toMatch(/dashboardPassword.*URL-safe/);
  });

  it('rejects any value containing a newline (would corrupt .env)', async () => {
    const r = await writeEnvFile({
      repoDir: dir,
      ...BASE,
      jwtSecret: 'has\nnewline',
    });
    expect(r.ok).toBe(false);
    expect(r.reason).toMatch(/jwtSecret/);
  });

  it('rejects a supabaseUrl containing shell metacharacters', async () => {
    const r = await writeEnvFile({ repoDir: dir, ...BASE, supabaseUrl: 'http://x;rm -rf /' });
    expect(r.ok).toBe(false);
    expect(r.reason).toMatch(/supabaseUrl/);
  });
});
